server:
  port: 80
---
spring:
  profiles:
    active: dev
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:config/mybatis/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 支持统配符 * 或者 ; 分割
  type-enums-package: com.choxsu.common.enums
  type-aliases-package: com.choxsu.common.entity
shiro:
  loginUrl: /login